env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[111c0c2f3915d20bf797b0d6cf6f5198a93902b4202d22acf19818c021831ce29fe7786f283098881e00f33d7c2dbf93]
    TG_TOKEN: ENCRYPTED[a2f800cd6af33a88069cb94c10234351c104162a073b72cfc263e0520545bea7afe0b466800fdd4ec46b9a60ee00af46]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  Checks_script:
      - bash $CIRRUS_WORKING_DIR/scripts/checks.sh

  Sync_script:
      - bash $CIRRUS_WORKING_DIR/scripts/sync.sh

  Build_script:
      - bash $CIRRUS_WORKING_DIR/scripts/build.sh

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash $CIRRUS_WORKING_DIR/scripts/upload.sh
