env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[5fa2845a631b96d18fdcb2d7f1062c82c532c24136e8be6f2362fe9b9edbf2a44c981e4914a01a6aef0c64df8e50e02c]
    TG_TOKEN: ENCRYPTED[f00a61838ac674230787240a0601174a509189bdeecc7a3c76e626f90bb3d4d76d96ceb9b05c57ec1b7d0a59310f6230]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Checks_script:
      - curl -sL https://raw.githubusercontent.com/NFS-projects/OrangeFox-CI/fox/scripts/checks.sh | bash

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/NFS-projects/OrangeFox-CI/fox/scripts/sync.sh | bash

  Build_script:
      - curl -sL https://raw.githubusercontent.com/NFS-projects/OrangeFox-CI/fox/scripts/build.sh | bash

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - curl https://raw.githubusercontent.com/NFS-projects/OrangeFox-CI/fox/scripts/upload.sh | bash
