env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Cirrus Specific Vars (Do *NOT* Change)
    WORKDIR: "/tmp"
    CIRRUS_CLONE_DEPTH: "1"
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: anggit86/ubuntu:22.04
      cpu: 8
      memory: 32G

  Checks_script:
      - bash $CIRRUS_WORKING_DIR/scripts/checks.sh

  Sync_script:
      - bash $CIRRUS_WORKING_DIR/scripts/sync.sh

  Build_script:
      - bash $CIRRUS_WORKING_DIR/scripts/build.sh

  Upload_script:
      - bash $CIRRUS_WORKING_DIR/scripts/upload.sh
