env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[b7cf3a86116a59a9b0ca082d06108b2c2a4cac1992037ecd9d39bf963c7810f3e06fd907ebdd688049279fade482eebd]
    TG_TOKEN: ENCRYPTED[b0f13e1e92714a7362d7818ed4ed0f97acb75cfaf54d959909bf8d7829a9ce32cd49d4d5d7ec6127fd7ad5d846a963c9]

    # Google Drive
    RCLONECONFIG_DRIVE: ENCRYPTED[abd6c3376f90c2d5c846e6b856c1d0e1856dd5ffe25b9137c672e601179cdcaceb731222fd0dd019f8bc5254616bc15f]

    # Cirrus Specific Vars (Do *NOT* Change)
    WORKDIR: "/tmp"
    CIRRUS_CLONE_DEPTH: "1"
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: anggit86/ubuntu:22.04
      cpu: 8
      memory: 32G

  Checks_script:
      - bash $CIRRUS_WORKING_DIR/scripts/checks.sh

  Sync_script:
      - bash $CIRRUS_WORKING_DIR/scripts/sync.sh

  Build_script:
      - bash $CIRRUS_WORKING_DIR/scripts/build.sh

  Upload_script:
      - bash $CIRRUS_WORKING_DIR/scripts/upload.sh
